### PR TITLE
[feature/urlImageAccessor] added a prop to customize images array url…

### PR DESCRIPTION
**Pull request by inspmoore**
Added a feature, where by passing a prop called `imageUrlAccessor` you can customize the field name in the images array responsible for the image url.

Example:
```
const images = [
  { image_uri: '...' },
  { image_uri: '...' ),
  ...
]

<ImageSlider images={images} imageUrlAccessor="image_uri" />
```
The prop defaults to "url" so this is not a breaking change. 

Sorry for the screwed up linting. Couldn't get it to work exactly like yours config.

### CODE REVIEW

**Review by kimcoder — COMMENTED** [review]
How about map a images array?
```
images={this.images.map((item) => ({ url: item.uri }))}
```

**Comment by inspmoore** [comment]
I agree that this is how it's done usually, but it's a bit costly operation when you have a large images array. Especially when you run it on a low end android device. This simple  feature allows to skip this step and is 100% backwards compatible with previous version.

**Comment by kimcoder** [comment]
Understood.
Unfortunatlely, Your PR has conflicted now. because I updated major version at yesterday. 
( developed by typescript, add lint, prettier. )
Can you resolve this conflicts ?
Thanks

**Comment by inspmoore** [comment]
Sure thing, will refactor the code for the new spec. Cool that the project is now on TS.

**Pull request closed without merging**
